config/routes.rb
Apps::Application.routes.draw do

  devise_for :owners

  namespace :admin_panel do
    root :to => "welcome#index"
    resources :welcome , :only =>[:index]
    resources :owners;
  end
  
  root :to => "welcome#index"

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    #  user ||= User.new # guest user (not logged in)
    #  if user.admin?
    #    can :manage, :all
    #  else
    #    can :read, :all
    #  end
    #
    # The first argument to `can` is the action you are giving the user 
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. 
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/owner.rb
class Owner < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
	layout "admin_panel"
	before_filter :authenticate_owner!
 
end

app/controllers/admin_panel/welcome_controller.rb
class AdminPanel::WelcomeController < AdminController
  def index
  	# list of model can managed it
  	@models = []
  	@tab_path = []
  	@data_tables = [] #ActiveRecord::Base.connection.tables
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  alias_method :current_user, :current_owner
  
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/admin_helper.rb
module AdminHelper

	def list
		if  eval('@'+controller.controller_name).nil? ||  eval('@'+controller.controller_name).blank?
			return []
		end
		liste = eval('@'+controller.controller_name).class.name == 'Array' ? (eval('@'+controller.controller_name)[0].nil? ? '' : eval('@'+controller.controller_name)[0].attributes.keys ) : eval('@'+controller.controller_name).attributes.keys
	   	
	   	@header = liste.map{|atr| {:name => atr, :value => atr}}
	   return  @header
	end

	def edit

	end

	def show
		if  eval('@'+controller.controller_name).nil? 
			return []
		end
		liste = eval('@'+controller.controller_name).class.name == 'Array' ? eval('@'+controller.controller_name)[0].attributes.keys : eval('@'+controller.controller_name).attributes.keys
	   	@header = liste.map{|atr| {:name => atr, :value => atr}}
	   return  @header
	end
	
	def title

	end

	def path obj
		return 'admin_panel_' + controller.controller_name + '_path'
	end

	def association obj
		eval("@#{controller.controller_name}").class.reflect_on_all_associations(&:name).reject(&:translations)
		#== 'Array' ? eval("@#{controller.controller_name}").send(p).first.id : eval("@#{controller.controller_name}").send(p).id
	end

	def path_controller
		return eval('admin_panel_' + controller.controller_name + '_index_path')
	end

	def add_link_list obj
		
  	end

  	def page_list
  		val = (@all_page / 10 )
  		result = []
  		for i in 0..val
   			result << [i+1 , (path_controller.include? '?') ? path_controller + "&page=" + i.to_s : path_controller + "?page=" + i.to_s]
		end
		return result
  	end

  	

end

app/helpers/admin_panel/welcome_helper.rb
module AdminPanel::WelcomeHelper
	#def current_user
  	#	current_owner
  	#end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/admin_panel/_info.html.slim
h3
  = title
br
table class="table"
  - show.each do |h|
    tr
      td
        = t("#{controller.controller_name}.#{h[:name]}")
      td
        - if !h[:prety].nil?
          = %{#{h[:prety].gsub('?',object[h[:value]].nil? ? '' : object[h[:value]])}}.html_safe
        - elsif !h[:default].nil?
          = eval("#{h[:default]}")
        - elsif !h[:def].nil?
          = send("#{h[:def]}",object)
        - else
          = object.send("#{h[:value]}")

app/views/admin_panel/_lang_tab.html.slim
.form-group
  ul#LangTab.nav.nav-tabs
    - @lang.each do |l|
      li class="#{ l == @lang.first ? 'active' : ''}"
        a href="##{l}"  data-toggle="tab"
          = l
  #myTabContent.tab-content
    - @lang.each do |l|
      div class="tab-pane #{ @lang.first == l ? 'active' : ''}" id="#{l}"
        = fal.globalize_fields_for l.to_sym do |fo|
          - edit_translate.each do |e|
            strong
              = t("#{controller.controller_name}.#{e[:name]}")
            - unless obj.errors.messages["#{e[:name]}".to_sym].blank?
              - unless obj.errors.messages["#{e[:name]}".to_sym][0].nil?
                .alert.alert-danger
                  abel.control-label
                    = obj.errors.messages["#{e[:name]}".to_sym][0]
            = fo.send("#{e[:type]}","#{e[:name]}".to_sym , :class => "form-control has-error" , :size => "10")
javascript:
  $('#LangTab a').click(function (e) {
    e.preventDefault()
    $(this).tab('show')
  })

app/views/admin_panel/_link_navbar.html.slim
-@models.each do |f| 
  -if f.class.name == 'Array'
    li
      a href="#"
        = t("models." + f[0].to_s ) 
      ul
        - f[1].each do |s|
          li
            a href="#{eval('admin_panel_'+ s + '_path')}" 
              = t("models." + s )	
  -else
    li
      a href="#{eval('admin_panel_'+ f + '_path')}" 
        = t("models." + f ) 

app/views/admin_panel/_list.html.slim
tr
  - @header.each do |h|   
    td
      - if !h[:prety].nil?
        = %{#{h[:prety].gsub('?',object[h[:value]].nil? ? '' : object[h[:value]])}}.html_safe
      - elsif !h[:default].nil?
        = eval("#{h[:default]}")
      - elsif !h[:def].nil?
        = send("#{h[:def]}",object)
      - else
        = object.send("#{h[:value]}")
  td
    span.right
      - if (can? :edit, object ) && (eval('edit_'+ path(object)) rescue false)
        a href="#{eval('edit_'+ path(object))}"
          span class="glyphicon glyphicon-pencil"
        |&nbsp;
      - if (can? :show, object) && (eval(path(object)) rescue false)
        a href="#{eval(path(object))}"
          span class="glyphicon glyphicon-info-sign"
        |&nbsp;
      - if (can? :delete, object ) && (eval('delete_'+ path(object)) rescue false)
        a href="#{eval('delete_'+ path(object))}"
          span class="glyphicon glyphicon-remove-circle"
/eval(object.class.name).respond_to?('edit')
/=# link_to 'Destroy', "#{eval(path.blank? ? 'admin_'+ controller.controller_name + '_path' : path )}/#{object.id}", method: :delete

app/views/admin_panel/delete.html.slim
= form_tag("#{(path_controller.include? '?') ? path_controller.gsub('?','/'+ eval('@'+controller.controller_name).id.to_s + '?') : path_controller + '/'+ eval('@'+controller.controller_name).id.to_s}", :method => "delete")
  div class="panel panel-warning"
    div class="panel-heading"
      = t('methods.destroy')
    div class="panel-body"
      = t('methods.delete')
      = eval("@#{controller.controller_name}").class.name
      br
      br
      button type="button" class="btn btn-primary" onClick="location.href='#{path_controller}'"
        = t("methods.cancel")
      |&nbsp;
      button type="submit" class="btn btn-danger"
        = t("methods.destroy")

app/views/admin_panel/index.html.slim
/= render :partial => "admin/shared/filtre"
table class="table"
  thead
    - list.each do |h|   
      th
        = t("#{controller.controller_name}.#{h[:name]}")
    th
  tbody
    = render :partial => "admin/list", :collection => eval("@#{controller.controller_name}") , :as => :object , :locals => {:tab => list }
.row
  .col-md-4.col-lg-3.col-sm-6.col-xs-8.center
    - unless @page.blank?
      = render :partial => "admin/shared/pagination"

app/views/admin_panel/shared/_filtre.html.slim
div class="panel panel-warning"
  div class="panel-body"
    /= form_for @contact , :url => create_path , method: :get  do |f|
    div class="form-group"
      input type="text" class="form-control" placeholder="Search"


app/views/admin_panel/shared/_image_list.html.slim
.row
  - images.each do |img|
    div class="col-sm-6 col-md-4"
      div class="thumbnail"
        = image_tag(img.url_url(:thumb),:'data-src' =>'holder.js/300x200' )
        div class="caption"
          h3
            = img.name
          p
            = img.description
          /p
            /a href="#" class="btn btn-primary" role="button"
            /  |Button
            /a href="#" class="btn btn-default" role="button"
            /  |Button
  

app/views/admin_panel/shared/_pagination.html.slim
ul class="pagination"
  - if @page > 0
    li
      a href="#{page_list[@page-1][1]}"
        |&laquo;
  - page_list.each do |p|
    li class="#{p[0]== @page+1 ? 'active' : ''}"
      a href="#{p[1]}"
        = p[0]
  - if @page < page_list.count - 1
    li
      a href="#{page_list[@page+1][1]}"
        |&raquo;

app/views/admin_panel/shared/_select.html.slim
table
  tr
    td
      SELECT.select_list  multiple="multiple" size="5" class="#{object}_first form-control "
        /optgroup label="tset"
        - first_list[0].each do |op|
          option value="#{op.read_attribute(first_list[1])}"
            = op.read_attribute(first_list[2])
    td
      .paddin
        button  class="round_bouton button_add" data="#{object}" type="button"
          span class="glyphicon glyphicon-circle-arrow-right"
        br
        button  class="round_bouton button_remove" data="#{object}" type="button"
          span class="glyphicon glyphicon-circle-arrow-left"
    td
      SELECT.select_list multiple="multiple" size="5" class="#{object}_last form-control middel_select" data=".#{object}_send"
        - unless last_list[:list].blank? && last_list[:list][0].blank?
          - last_list[:list][0].each do |op|
            option value="#{op.read_attribute(last_list[:list][1])}" selected=""
              = op.read_attribute(last_list[:list][2])
      SELECT.select_list id="#{last_list[:id]}" name="#{last_list[:name]}" multiple="multiple" size="5" class="#{object}_send  form-control " style="display: none;"
        - unless last_list[:list].blank? && last_list[:list][0].blank?
          - last_list[:list][0].each do |op|
            option value="#{op.read_attribute(last_list[:list][1])}" selected=""
              = op.read_attribute(last_list[:list][2])
/strong
/    | Option
/  = render :partial => "admin/shared/select" , :locals => {:first_list => [@list_option ,:id,:name], :last_list =>{:id=>"room_option",:name=>"room_option[]",:list=>[@hotel.hotels_refs.room_options.map{ |p| p.room_option_ref},:id,:name]} , :object => "option" }

app/views/admin_panel/show.html.slim
= render :partial => "admin/info" , :locals => { :object => eval("@#{controller.controller_name}")}

app/views/admin_panel/welcome/index.html.slim
- @data_tables.each do |dt| 
  br
  = dt
  br

app/views/layouts/admin_panel.html.slim
DOCTYPE html
html
head
  title
    |Apps
  = stylesheet_link_tag "en/application", :media => "all"
  = javascript_include_tag "application"
  = csrf_meta_tags
body
  header
  #wrapper
    #sidebar-wrapper
      ul.sidebar-nav
        li.sidebar-brand
          .pannel_title
            = link_to("<span class='label label-warning'>Logout</span>".html_safe, destroy_owner_session_path, :method => :delete)
        li= render :partial => "admin_panel/link_navbar"
    /! Page content
    #page-content-wrapper
      br
      br
      br
      - if !@error.nil?
        div class="alert alert-danger" 
          = @error
      .content-header
        h1
          a#menu-toggle.btn.btn-default href="#"
            i.icon-reorder
              | Menu
      ol class="breadcrumb"
        - a = '/'
        - @tab_path.each do |link|
          li
            a href= "#{a + link + (params[:locale].blank? ? '' : '?locale=' + params[:locale].to_s)}"
              = link
          - a+= link + '/'
        li class="active"
          = controller.action_name == 'index' ? '' : controller.action_name
      .page-content.inset
        - if controller.action_name == 'index' || controller.action_name == 'new'
          ul id="myTab" class="nav nav-tabs"
            li class="#{controller.action_name == 'index' ? 'active' : ''}"
              a href="#{path_controller}"
                span class="List glyphicon glyphicon-th-list"
                | &nbsp;&nbsp;
                = t("methods.list")
            - if (can? :new, eval("@"+controller.controller_name))
              li class="#{controller.action_name == 'index' ? '' : 'active'}"
                a href="#{(path_controller.include? '?') ? path_controller.gsub('?','/new?') : path_controller + '/new'}"
                  span class="glyphicon glyphicon-plus-sign"
                  | &nbsp;&nbsp;
                  = t("methods.new")
          div id="myTabContent" class="tab-content"
            div class="tab-pane fade active in" id="List"
              p
                == yield
        - else
          p
           == yield
    /! JavaScript
    javascript:
      $("#menu-toggle").click(function(e) {
           e.preventDefault();
           $("#wrapper").toggleClass("active");
       });

app/views/layouts/application.html.slim
DOCTYPE html
html
head
  title
    |Apps
  = stylesheet_link_tag "en/application", :media => "all"
  = javascript_include_tag "application"
  = csrf_meta_tags
body.body-back
  == yield

app/views/welcome/index.html.slim
h1 Welcome#index
p Find me in app/views/welcome/index.html.slim